models/ItemsModel.php
<?php

namespace app\models;

use yii\db\ActiveRecord;
use app\models\CatsModel;
use app\models\ItemsSameItemsModel;
use app\models\ItemsSizesClass;
use app\models\OrderItemsModel;
use app\models\PropsModel;
use app\models\SlugsModel;
use app\models\ItemsTagsClass;
use app\models\ItemsComplectItemsModel;

class ItemsModel extends ActiveRecord
{

    public static function tableName()
    {
        return 'items'; // TODO: Change the autogenerated stub
    }

    public function getCat() {
        return $this->hasOne(CatsModel::className(),['id'=>'cat_id']);
    }

    public function getSubCat() {
        return $this->hasOne(CatsModel::className(), ['id'=>'add_cat_id']);
    }

    public function getItemColors() {

        return $this->hasMany(ItemsColorsModel::className(),['item_id'=>'id'])->orderBy(['ord'=>SORT_ASC]);
    }

    public function getSameItems() {
        return $this->hasMany(ItemsSameItemsModel::className(),['same_item_id'=>'id']);
    }

    public function getItemSizes() {
        return $this->hasOne(ItemsSizesClass::className(),['item_id'=>'id']);
    }

    public function getOrderItem() {
        return $this->hasOne(OrderItemsModel::className(),['item_id'=>'id']);
    }

    public function getPropMatherial() {
        return $this->hasOne(PropsModel::className(), ['id'=>'prop_matherial']);
    }

    public function getPropPackage() {
        return $this->hasOne(PropsModel::className(),['id'=>'prop_package']);
    }

    public function getSlug() {
        return $this->hasOne(SlugsModel::className(),['object_id'=>'id'])->andWhere(['subject_id'=>4]);
    }

    public function getTags() {
        return $this->hasMany(ItemsTagsClass::className(),['item_id'=>'id']);
    }

    public function getComplectItems() {
        return $this->hasMany(ItemsComplectItemsModel::className(),['item_id'=>'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\CitiesModel;
use app\models\ItemsModel;
use app\models\ItemsSizesClass;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use app\models\CartModel;
use app\models\ClientModel;
use app\models\ItemClass;
use app\models\ItemColorClass;
use app\models\SlugModel;
use YandexCheckout\Client;
use app\models\CachePagesModel;
use app\models\LoginForm;
use PHPExcel;
use PHPExcel_Cell;
use PHPExcel_IOFactory;
use PHPExcel_RichText;
use PHPExcel_Style_Alignment;
use PHPExcel_Style_Border;
use PHPExcel_Style_Color;
use PHPExcel_Style_Fill;
use PHPExcel_Worksheet;
use PHPExcel_Worksheet_Drawing;
use PHPExcel_Worksheet_PageSetup;
use app\models\SlugsModel;
use Yii\helpers\ExcelHelpers;


class SiteController extends Controller
{

    public function __construct($id,$module,$config=[]) {

        // поиск телефона города
        parent::__construct($id,$module,$config);
    }
    public function init() {
        parent::init();
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $this->layout='new_desing';
        return $this->render('static/index', []);
    }

    public function actionCity($city) {
        $cookies = Yii::$app->response->cookies;
        $cookies->remove('city');
        $cookies->add(new \yii\web\Cookie(['name' => 'city','value' => $city]));
        $string=explode("/",$_SERVER['HTTP_REFERER']);
        $city=CitiesModel::find()->where(['title'=>$city])->one();
        if($city['subdomain']=='') {
            $url="http://oporu.ru";
        } else {
            $url="http://oporu.ru";
        }
        for($i=3;$i<sizeof($string);++$i) {
            $url.="/".$string[$i];
        }
        return $this->redirect($url);
    }

    public function actionCompare($print=NULL, $excel=NULL) {
        $request=Yii::$app->request;
        if($request->post() && $request->post("id")) {
            $id = $request->post("id");
            $session = Yii::$app->session->getId();
            $key = "compare_" . $session;
            $cache = Yii::$app->cache;
            $data = $cache->get($key);
            if ($data === false) {
                $data[$id] = $id;
                $cache->set($key, $data);
            } else {
                if (isset($data[$id])) {
                    unset($data[$id]);
                } else {
                    $data[$id] = $id;
                }
            }
            $cache->set($key, $data);
            return true;
        }
        if($request->get()) {
            $print=$request->get('print');
            $excel=$request->get('excel');
            Yii::$app->params['print']=true;
            $data['catalog_items']=ClientModel::getCompareItems();
            if($excel==1) {
                ExcelHelpers::CompareExcel($data);
                die;
            }
            if($print==1) {
                $this->layout='print';
                return $this->render('compare_print', ['catalog_element'=>$data]);
            }
            return $this->render('compare', ['catalog_element'=>$data]);
        }
    }

    public function actionCode($code) {
        if($code!==NULL) {
            $items = ItemsModel::find()->where(['code' => $code])->all();
            //print_r($items);
            return $this->render('items-code', ['items'=>$items,'title'=>$code]);
        }
        throw new NotFoundHttpException;
    }

    public function actionCart($print=NULL, $excel=NULL) {
        $request=Yii::$app->request;
        $action=$request->post("action");
        if($action=="addItem") {
            $id=$request->post("id");
            $quantity=$request->post("quantity");
            if(CartModel::addToCart($id,$quantity)) {
                return "Товар Добавлен";
            } else {
                return "Товар не добавлен";
            }
        }
        if($action=="addFreeItem") {
            $id=$request->post("id");
            $quantity="free";
            if(CartModel::addToCart($id,$quantity)) {
                return "Товар Добавлен";
            } else {
                return "Товар не добавлен";
            }
        }
        if($action=="deleteItem") {
            $id=$request->post("id");
            if(CartModel::deleteCart($id)) {
                return $id;
            } else {
                return "No delete";
            }
        }
        if($action=="flushItem") {
            if(CartModel::flushCart()) {
                return "Всё ок";
            } else {
                return "Всё не ок";
            }
        }
        // в yandex-pay-controller
        if($action=="pay-online") {
            /*$client = new Client();
            $client->setAuth('625523', 'test_M0IfmOvTcWadWkLWwKJjf6hTG8CReNaWSEKr5QT2jlI');
            $idempotenceKey = uniqid('', true);
            $response = $client->createPayment(
                array(
                    'amount' => array(
                        'value' => '2.00',
                        'currency' => 'RUB',
                    ),
                    'payment_method_data' => array(
                        'type' => 'bank_card',
                    ),
                    'confirmation' => array(
                        'type' => 'redirect',
                        'return_url' => 'https://dev.zaglushka.ru/return_url',
                    ),
                    'description' => 'Заказ №72',
                ),
                $idempotenceKey
            );*/
            //$confirmationUrl = $response->getConfirmation()->getConfirmationUrl();
            //return $confirmationUrl;
        }
        if($action=="addForm") {
            $id=$request->post("id");
            $itemData=ItemClass::getItemData($id);
            $itemColorData=ItemColorClass::getItemColorData($id);
            return $this->renderPartial('add-to-cart', ['itemData'=>$itemData, 'itemColorData'=>$itemColorData]);
        } else {
            Yii::$app->params['print']=true;
            $print=$request->get('print');
            $excel=$request->get('excel');
            if($excel==1) {
                ExcelHelpers::CartExcel(CartModel::getCart());
                die;
            }
            if($print==1) {
                $this->layout='print';
                return $this->render('cart_print', ['cart'=>(CartModel::getCart()) ? CartModel::getCart() : NULL]);
            }
            return $this->render('cart', ['cart'=>(CartModel::getCart()) ? CartModel::getCart() : NULL]);
        }
    }
    
    public function actionPay() {
        $top_menu=ClientModel::getAllCatalogElement(); 
        Yii::$app->params['catalog_element']=$top_menu;
        return $this->render('pay', []);
    }
    
    public function actionBooklet() {
        $top_menu=ClientModel::getAllCatalogElement(); 
        Yii::$app->params['catalog_element']=$top_menu;
        return $this->render('booklet', []);
    }
    
    public function actionDelivery() {
        $top_menu=ClientModel::getAllCatalogElement(); 
        Yii::$app->params['catalog_element']=$top_menu;
        return $this->render('delivery', []);
    }
    
    public function actionContacts() {
        $top_menu=ClientModel::getAllCatalogElement(); 
        Yii::$app->params['catalog_element']=$top_menu;
        return $this->render('contacts', []);
    }

    public function actionSpecial() {

    }
    
    public function actionSearch() {
        $cache=Yii::$app->cache;
        $top_menu=ClientModel::getAllCatalogElement(); 
        Yii::$app->params['catalog_element']=$top_menu;
        $autocomplete=[];
        $filters=[];
        $items=json_decode($cache->get("Items"),true);
        foreach($items as $item) {
            $autocomplete[]=$item['code'];
            $autocomplete[]=$item['title'];

        }
        $itemsFiltes=[];
        $items_sizes=json_decode($cache->get("ItemsSizes"),true);
        foreach($items_sizes as $filter_type => $itemSize) {
            $filters[$filter_type]['filter']=$itemSize;
            $itemsFiltes[$filter_type]=$itemSize;
        }
        $request=Yii::$app->request;
        $search_string=$request->get('search_string');
        if($search_string!==FALSE and strlen($search_string)>0) {
            // убираем запрос

            $items=ItemsModel::find()->where("`code` = '{$search_string}' OR `title`='{$search_string}' OR (`short_descr` LIKE '%{$search_string}%')")->all();
            $search_result=[];
            foreach($items as $item) {
                $search_result[$item->cat->parent->title][]=$item;
            }
        }
        $filter_type=$request->get('filter_type');
        if($filter_type!==FALSE and strlen($filter_type)>0) {
            $filter_id=[];
            $filter_size_1=$request->get('size_1');
            $filter_size_2=$request->get('size_2');
            $filter_size_3=$request->get('size_3');

views/site/add-to-cart.php
<?php

use yii\helpers\Url;
use app\assets\AppAsset;
AppAsset::register($this);
/* @var $this yii\web\View */

$this->title = 'Корзина';
$additionalPrices = [
        0 => 0,
        1 => 20,
        2 => 30,
        7 => 35,
        8 => 40,
        9 => 10,
        3 => 50,
        4 => 70,
        5 => 100,
        6 => 200
    ];
?>
<div class="add-to-cart-form">
    <div class="close-cart-form">
        <a href="#">Закрыть</a>
    </div>
    <div class="cart-form">
        <input type="hidden" name="itemId" id="itemId" value="<?= $itemData['id']; ?>" />
        <table style="width:100%;">
            <thead>
                <tr>
                    <td>Фото</td>
                    <td>Артикул</td>
                    <td>Описание</td>
                    <td>Цвет</td>
                    <td>Количество, штук</td>
                    <td>Цена за штуку</td>
                    <td>Сумма</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="cart-form-image"><img src="https://zaglushka.ru/images/item/<?php echo substr($itemData['id'], -2); ?>/<?= $itemData['id']; ?>/5.jpg"</td>
                    <td class="cart-form-title"><span>Артикул:</span><span><?= $itemData['title']; ?></span></td>
                    <td class="cart-form-description"><?= $itemData['short_descr']; ?></td>
                    <td class="cart-form-color-select">
                        <span>Цвет:</span>
                        <div class="cart-form-color-select-area">
                            <select class="change_color_cart">
                                <?php foreach($itemColorData as $color): ?>
                                <option value="<?= $color['items_colors_id']; ?>" data-remains="<?= $color['remains']; ?>" data-title="<?= $color['code']; ?>" data-addPrice="<?= $additionalPrices[$color['addprice']]; ?>" data-price0="<?= $itemData['price0']; ?>" data-price1="<?= $itemData['price1']; ?>" data-price2="<?= $itemData['price2']; ?>" data-price3="<?= $itemData['price3']; ?>" data-price4="<?= $itemData['price4']; ?>" data-price5="<?= $itemData['price5']; ?>" data-colorName="<?= $color['colorname']; ?>"><?= $color['colorname']; ?></option>
                                <?php endforeach; ?>
                            </select>
                            <svg class="icon icon_arrows icon_arrows_select">
                                <use xlink:href="/images/sprite.svg?id=a471817642adde4a4e32#arrows"></use>
                            </svg>
                        </div>
                        <div class="cart-form-color-select-remains-area">
                            В наличии:<br />
                            <strong class="cart-form-color-select-remains-value"></strong>
                        </div>
                    </td>
                    <td class="cart-form-quantity">
                        <span>Количество штук:</span>
                        <input type="number" class="quantity" min="1" max="1000000"/>
                    </td>
                    <td class="cart-form-oneprice">
                        <span>Цена за штуку:</span>
                        <div class="cart_one_price">

                        </div>
                    </td>
                    <td class="cart-form-allprice">
                        <span>Сумма:</span>
                        <div class="cart_total_price"></div>
                    </td>
                </tr>
            </tbody>
        </table>
        <hr />
        <div class="addToCartContainer">
            <button class="addToCart">Добавить в корзину</button>
        </div>
    </div>
    
</div>

<script>
$(function() {
    function disableScrolling(){
        var x=window.scrollX;
        var y=window.scrollY;
        window.onscroll=function(){window.scrollTo(x, y);};
    }

    function enableScrolling(){
        window.onscroll=function(){};
    }
    function formValidate() {
        // здесь валидация
    }
    function calcPrice() {
        var one_price=0;
        var total=0;
        var objSelect=$(".change_color_cart option:selected");
        var addPrice=parseFloat(objSelect.attr('data-addPrice'));
        var price0=parseFloat(objSelect.attr('data-price5'));
        var price1=parseFloat(objSelect.attr('data-price4'));
        var price2=parseFloat(objSelect.attr('data-price3'));
        var price3=parseFloat(objSelect.attr('data-price2'));
        var price4=parseFloat(objSelect.attr('data-price1'));
        var price5=parseFloat(objSelect.attr('data-price0'));
        var quantity=parseInt($(".quantity").val());
        addPrice=1+(addPrice/100);
        if(quantity<=100) {
            one_price=price5*addPrice;
            total=quantity*one_price;
        } 
        if(quantity>100 && quantity<=500) {
            one_price=price4*addPrice;
        }  
        if(quantity>500 && quantity<=1000) {
            one_price=price3*addPrice;
        }  
        if(quantity>1000 && quantity<=5000) {
            one_price=price2*addPrice;
        }  
        if(quantity>5000 && quantity<=10000) {
            one_price=price1*addPrice;
        }  
        if(quantity>10000) {
            one_price=price0*addPrice;
        } 
        total=quantity*one_price;
        if(addPrice>0 && quantity>0)
        {
            $(".cart_one_price").html(one_price.toFixed(2));
            $(".cart_total_price").html(total.toFixed(2));
        } else {
            $(".cart_one_price").html();
            $(".cart_total_price").html();
        }
    }
    $(".change_color_cart").on("change", function(){
        $(".cart_one_price").html('');
        $(".cart_total_price").html('');
        $(".cart-form-color-select-remains-value").html('');
        var selectedObj=$(this).find("option:selected");
        var remains=parseInt(selectedObj.attr("data-remains"));
        if(remains>0) {
            $(".cart-form-color-select-remains-area").show();
            $(".cart-form-color-select-remains-value").html(remains.toLocaleString()+" шт.");
        } else {
            $(".cart-form-color-select-remains-area").hide();
        }
        calcPrice();
    });
    $(".quantity").on("input", function(){
        var quantity=parseInt($(".quantity").val());
        console.log(quantity);
        if(quantity>0) {
            calcPrice();
        } else {
            $(".cart_one_price").html('');
            $(".cart_total_price").html('');
        }
    });
    $(".close-cart-form").on("click", function() {
        $(".overlay").hide();
        $(".overlay .popup_container").html();
        enableScrolling();
    });
    $(".addToCart").on("click", function() {
        var quantity=parseInt($(".quantity").val());
        var colorId=parseInt($(".change_color_cart option:selected").val());
        if(quantity>0 && colorId>0) {
            $.post("/cart", { id: colorId, quantity: quantity, action: "addItem" }).done(function(data) {
                $(".popup_cart").slideDown(300);
                $(".overlay").hide();
                $(".overlay .popup_container").html();
                enableScrolling();
                var quantity=parseInt($(".quantity").val());
                $(".js-nav-cart-count").html(parseInt($(".js-nav-cart-count").html())+quantity);
                var sum=$(".cart_total_price").html();
                var img_link=$(".cart-form-image img").attr("src");
                var colorName=$(".change_color_cart option:selected").attr("data-colorName");
                $(".popup_cart_header_table_data_image img").attr("src", img_link);
                $(".popup_cart_header_table_data_color span").html(colorName);
                $(".popup_cart_header_table_data_quantity span").html(quantity);
                $(".popup_cart_header_table_data_price span").html(sum);
                $(".popup_cart").delay(10000).slideUp(300);
            });
        }
        if(colorId>0) {
            $(".change_color_cart").focus();
        }
        if(quantity>0) {
            $(".quantity").focus();
        }
    });
});
</script>

views/site/cart_print.php
<?php

use yii\helpers\Url;
use app\assets\AppAsset;
use yii\web\JqueryAsset;

AppAsset::register($this);
JqueryAsset::register($this);
?>
    <table class="header">
        <tbody>
            <tr class="header__row">
                <td class="header__logo">
                    <img src="https://zaglushka.ru/images/logo_print.png">
                </td>
                <td class="header__address">
                    <strong>ОТДЕЛ ПРОДАЖ</strong>
                    <br>
                    <strong>тел. 7 (812) 242-80-99</strong>
                    <br>
                    <strong>тел. 7 (800) 555-04-99</strong>
                    <br>
                    <br>
                    <p>
                        <strong>АДРЕС СКЛАДА:</strong>
                        <br>
                        г. Санкт-Петербург, п. Парголово ул. Подгорная, дом 6. Въезд с ул. Железнодорожная, дом 11 На территории АНГАР № 12 График работы: Пн-Пт, 9:00 - 18:00
                    </p>
                </td>
                <td class="header__contacts">

                </td>
            </tr>
        </tbody>
    </table>
<br /><br />
    <main>
    <?php if(sizeof($cart)>0): ?>
        <table class="list" width="100%">
            <thead>
            <tr>
                <th>№</th>
                <th>Фото</th>
                <th>Артикул</th>
                <th>Описание</th>
                <th>Цвет</th>
                <th class="nowrap">Кол-во штук</th>
                <th>Оптовая группа</th>
                <th class="nowrap">Цена за 1 штуку</th>
                <th>Сумма</th>
            </tr>
            </thead>
            <tbody>
                <?php $i=1; ?>
                <?php $all=0; ?>
                <?php foreach($cart as $cart_element): ?>
                <tr>
                    <td><?= $i; ?></td>
                    <td>
                        <?php
                            if(substr($cart_element['item']['items_id'], -2)=="00") {
                                $imagePath="/images/item/0/".$cart_element['item']['items_id']."/";
                            } else {
                                $imagePath="/images/item/".substr($cart_element['item']['items_id'], -2)."/".$cart_element['item']['items_id']."/";
                            }
                        ?>
                        <?php $img="{$imagePath}1.jpg"; ?>
                        <?php if (file_exists($_SERVER['DOCUMENT_ROOT'].$img)): ?>
                            <img src="<?= $img; ?>" alt="4НЧК" width="95" height="95">
                        <?php else: ?>
                            <img class="product-table__image" src="https://zaglushka.ru/images/dummy_95.png" alt="" height="95" width="95">
                        <?php endif; ?>
                    </td>
                    <?php if($cart_element['quantity']=="free"): ?>
                        <td>
                            <?= $cart_element['item']['items_colors_code']; ?>
                        </td>
                        <td>
1
                        </td>
                        <td>
                            <?= $cart_element['item']['colorname']; ?>
                        </td>
                        <td colspan="4">
                            Бесплатные образцы
                        </td>
                    <?php else: ?>
                        <?php
                            $group_num=0;
                            if($cart_element['quantity']<100) {
                                $group_num=0;
                                $group_name="розница";
                            }
                            if($cart_element['quantity']>=100 && $cart_element['quantity']<500) {
                                $group_num=1;
                                $group_name="от 100 до 500";
                            }
                            if($cart_element['quantity']>=500 && $cart_element['quantity']<1000) {
                                $group_num=2;
                                $group_name="от 500 до 1000";
                            }
                            if($cart_element['quantity']>=1000 && $cart_element['quantity']<5000) {
                                $group_num=3;
                                $group_name="от 1000 до 5000";
                            }
                            if($cart_element['quantity']>=5000 && $cart_element['quantity']<10000) {
                                $group_num=4;
                                $group_name="от 5000 до 10000";
                            }
                            if($cart_element['quantity']>=10000) {
                                $group_num=5;
                                $group_name="от 10000";
                            }
                        ?>
                        <td>
                            <?= $cart_element['item']['items_colors_code']; ?>
                        </td>
                        <td>
                            1
                        </td>
                        <td>
                            <?= $cart_element['item']['colorname']; ?>
                        </td>
                        <td>
                            <?= $cart_element['quantity']; ?>
                        </td>
                        <td>
                            <?= $group_name; ?>
                        </td>
                        <td>
                            <?= $cart_element['item']['price'.$group_num]; ?> р.
                        </td>
                        <td>
                            <?php $sum=$cart_element['item']['price'.$group_num]*$cart_element['quantity']; ?>
                            <?= $sum; ?> р.
                            <?php $all=$all+$sum; ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <p class="total">
            Стоимость продукции: <?= $sum; ?> руб.
        </p>
    <?php endif; ?>
        <p>
            До бесплатной доставки "до дверей" в городе Санкт-Петербург в заказе не хватает товаров на сумму 3 080 рублей.
        </p>
        <p>Бесплатная доставка не распространяется на горки, канаты "Викинг", стальные цепи, сиденья и каркасы для стульев.</p>
    </main>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/items-code.php
<?php

use yii\helpers\Url;
use yii\widgets\LinkPager;
use yii\web\JqueryAsset;
use yii\bootstrap\Tabs;
use yii\jui\Accordion;
use app\models\ItemsModel;
/* @var $this yii\web\View */

$this->title="Модель: ".$title;
/*for($i=sizeof($catalog_element['breadcrumbs'])-1;$i>=0;$i--){
    $this->params['breadcrumbs'][] = array(
        'label'=> $catalog_element['breadcrumbs'][$i]['title'],
        'url'=>$catalog_element['breadcrumbs'][$i]['url']
    );
}*/
$additionalPrices = [
    0 => 0,
    1 => 20,
    2 => 30,
    7 => 35,
    8 => 40,
    9 => 10,
    3 => 50,
    4 => 70,
    5 => 100,
    6 => 200
];
?>

<div class="item_title_mob">
    <div class="item_title_mob--back">
        <a href="/">
            <svg class="p-main-catalog__link-mob-icon icon icon_arrow-bredcrumbs2">
                <use xlink:href="/images/sprite.svg?id=a471817642adde4a4e32#arrow-braedcrumbs2"></use>
            </svg>
        </a>
    </div>
    <div class="item_title_mob--value">
        <span>"Модель: <?= $title; ?>"</span>
    </div>
    <div class="item_title_mob--filters">

    </div>
</div>
<div class="item_content">
    <div class="item_title" style="flex-basis: 100%;">Модель: <?= $title; ?></div>
    <div class="item_photo">
        <div class="item_photo_carousel">

        </div>
    </div>
    <div class="item_description">
        <div class="item_articul">
            <table border="1" width="100%;">
                <tr>
                    <td rowspan="2">Артикул</td>
                    <td colspan="1">Размеры</td>
                    <td colspan="7">Цены</td>
                    <td rowspan="2"></td>
                </tr>
                <tr>
                    <td>ØD</td>
                    <td>до 100</td>
                    <td>от 100 до 500</td>
                    <td>от 500 до 1000</td>
                    <td>от 1000 до 5000</td>
                    <td>от 5000 до 10000</td>
                    <td>от 10000</td>
                </tr>
            <?php foreach($items as $item): ?>
            <tr>
                <td><?= $item->title; ?></td>
                <td><?= $item->itemSizes->size_1; ?></td>
                <td><?= $item->price0; ?></td>
                <td><?= $item->price1; ?></td>
                <td><?= $item->price2; ?></td>
                <td><?= $item->price3; ?></td>
                <td><?= $item->price4; ?></td>
                <td><?= $item->price5; ?></td>
                <td>Заказать</td>
            </tr>
            <?php endforeach; ?>
            </table>
        </div>
        <div class="order-container">
            <div class="free-item">
            </div>
            <div class="item-order">
                <a href='#' class="add_to_cart" data-id=''>Заказать</a>
            </div>
        </div>
    </div>
    <div class="item_content_text">

    </div>
</div>